---
title: "Statistical Inference Course Project1"
author: "doyougnu"
date: "July 20, 2015"
output: pdf_document
---

###Overview
Overview to be writting here...

###Simulations
```{r Simulations, echo = TRUE}
#set seed
set.seed = 1234

#number of simulations to run
simnum <- 1000

#number of distributions to generate
exp_n <- 40

#exponential distribution parameters
exp_lambda <- 0.2
expMean <- NULL
expVar <-NULL
for (a in 1:simnum) {
    expMean = c(expMean, mean(rexp(exp_n, exp_lambda)))
    expVar = c(expVar, var(rexp(exp_n, exp_lambda)))
}
```

###Plots Comparing Simulation to Population
```{r meanPlot, echo = TRUE}
#load ggplot2
library(ggplot2)

#Compare Means
popMean <- 1 / exp_lambda
simMean <- mean(expMean)
popMean
simMean

#Compare Means visually
plt <- qplot(expMean) + 
    xlab("Mean of 40 Exponential Samples") +
    ggtitle("Distribution of Sample Means") +
    geom_vline(xintercept = 1 / exp_lambda, colour = "red", size = 2) +
plt
```

```{r varPlot, echo = TRUE}
#Compare Variances
popVariance <- (1 / exp_lambda) ^ 2
simVariance <- mean(expVar)
popVariance
simVariance

#compare Variances visually
plt.two <- qplot(expVar, main = "Distribution of Sample Variances") +
    xlim(0, 150) +
    xlab("Variance of 40 Exponential Samples") +
    geom_vline(size = 2, xintercept = (1 / exp_lambda)^2, colour = "red")
plt.two
```

###Comparison between Random Variables and Sample Distributions
```{r compPlots, echo = TRUE, fig.height=10, fig.width=10}
#load libs
library(gtable)
library(gridExtra)

#Make 1000 Exponentials
r1 <- qplot(rexp(simnum, exp_lambda),  
            main = "1000 Random Exponentials") +
    xlab("Random Generated Exponential Deviates") 

#plot
grid.arrange(r1, plt, plt.two)
```
